version: '2'
services:
  nginx:
      container_name: nginx
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "80:80"
      restart: always

  app:
    container_name: app
    image: bitnami/mongodb:4.0
    ports:
      - "27017"
    volumes:
      - 'bitnami_db-volume:/bitnami'
    env_file:
      - ./node.env
    networks:
      app-network:
    depends_on:
      - nginx
      - primary
    restart: always

  primary:
    container_name: primary
    image: bitnami/mongodb:4.0
    ports:
      - "30001:27017"
    volumes:
      - 'bitnami_db-volume:/bitnami'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=password123
    networks:
      app-network:
    restart: always

  secondary1:
    container_name: second-db
    image: bitnami/mongodb:4.0
    ports:
      - "30002:27017"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=secondary1
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=password123
      - MONGODB_PRIMARY_HOST=primary
    networks:
      app-network:
    restart: always

  secondary2:
    container_name: third-db
    image: bitnami/mongodb:4.0
    ports:
      - "30003:27017"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=secondary2
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_PRIMARY_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_KEY=password123
      - MONGODB_PRIMARY_HOST=primary
    networks:
      app-network:
    restart: always

networks:
  app-network:

volumes:
  bitnami_db-volume:
    driver: local
