version: '2'
services:
  nginx:
      container_name: nginx
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "8000:80"
      networks:
        my-network:
      restart: always

  my-node-app:
    container_name: my-node-app
    image: osherbaruch/weather_image:1.0.7
    ports:
      - "3000"
    env_file:
      - .env
    depends_on:
      - nginx
      - mongo-practice2
    networks:
      my-network:
    restart: always

  mongo-practice2:
    container_name: mongo-practice2
    image: bitnami/mongodb:4.0
    ports:
      - "30001:27017"
    volumes:
      - 'mongo-practice2_mongodb_data:/bitnami'
    environment:
      - MONGODB_ROOT_PASSWORD=password123
    networks:
      my-network:
    restart: always

networks:
  my-network:

volumes:
  mongo-practice2_mongodb_data:
    driver: local
